newenv/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    
	
	path('', views.cart_details, name='cart_details'),
	path('summary', views.cart_summary, name='cart_summary'),
	path('totalcart', views.total_cart, name='totalcart'),
	path('add/<int:bookid>', views.cart_add, name='cart_add'),
	path('remove/<int:bookid>', views.cart_remove, name='cart_remove'),
	path('update/<int:bookid>/<int:quantity>', views.cart_update, name='cart_update'),
 	path('remove/<int:bookid>/', views.cart_remove, name='cart_remove'),
 
 
]

newenv/order/urls.py
from django.urls import path
from . import views

app_name = 'order'

urlpatterns = [
	path('', views.order_list, name="order_list"),
	path('<int:id>', views.order_details, name="order_details"),
	path('shipping/', views.order_create, name="order_create"),
	path('pdf/<int:id>',views.pdf.as_view(), name="pdf"),
]

newenv/cart/models.py
from django.db import models

# Create your models here.

newenv/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from store.models import Book, Category
from .cart import Cart

from django.conf import settings
from django.http import JsonResponse


# class Cart(object):
#     def __init__(self, request):
#         self.session = request.session
#         cart = self.session.get(settings.CART_SESSION_ID)
#         if not cart:
#             cart = self.session[settings.CART_SESSION_ID] = {}
#         self.cart = cart


#     def add(self, book):
#         book_id = str(book.id)
#         if book.is_available() and book_id not in self.cart:
#             self.cart[book_id] = {'quantity': 0, 'price': str(book.price)}
#             self.cart[book_id]['quantity'] = 1
#             self.save()
#             return {'is_available': True}
#         else:
#             return {'is_available': False}

#     def save(self):
#         self.session[settings.CART_SESSION_ID] = self.cart
#         self.session.modified = True

def cart_add(request, bookid):
    cart = Cart(request)  
    book = get_object_or_404(Book, id=bookid) 
    response_data = cart.add(book=book)
    return JsonResponse(response_data)


def cart_update(request, bookid, quantity):
	cart = Cart(request) 
	book = get_object_or_404(Book, id=bookid) 
	cart.update(book=book)
	price = (book.price)

	return render(request, 'cart/price.html', {"price":price})

def cart_remove(request, bookid):
    cart = Cart(request)
    book = get_object_or_404(Book, id=bookid)
    cart.remove(book)
    return redirect('cart:cart_details')

def total_cart(request):
	return render(request, 'cart/totalcart.html')

def cart_summary(request):

	return render(request, 'cart/summary.html')

def cart_details(request):
	cart = Cart(request)
	context = {
		"cart": cart,
	}
	return render(request, 'cart/cart.html', context)

newenv/cart/templates/cart/cart.html
{% extends 'store/base.html' %}

			{% block container %}
			<div class="row">
				<div class="col-sm-8">
					<div class="cart_info">
					    <table class="table table-hover">
					        <thead class="text-center">
					            <tr>
					                <th scope="col">#</th>
					                <th scope="col" style="width: 250px">Nom</th>
					               
					                <th scope="col">Prix</th>
					                <th scope="col">Action</th>
					            </tr>
					        </thead>
					        <tbody class="text-center">
					        {% for item in cart %}
					        	{% with book=item.book %}
				           		 <tr>
					                <td class="cart_coverpage"><a href=""><img src="{{ book.coverpage.url }}"></a></td>
					                <td>{{ book.name }}</td>
					                <td id="{{ book.id }}">{{ item.total_price }} DH.</td>
					                <td><a href="{% url 'cart:cart_remove' bookid=book.id %}" class="btn btn-danger"><i class="fa fa-trash-o"></i></a></td>
					            </tr>
					            {% endwith %}
					        {% endfor %}
					        </tbody>
					    </table>
						<div class="continue_or_next text-center">
							<a href="{% url 'store:index' %}" class="btn _to_shope">Continuer vers Shope</a>
							<a href="{% url 'order:order_create' %}" class="btn _to_continue">Passer à la caisse</a>
						</div>
					</div>
				</div>
				<div class="col-sm-4" id="abc">

				</div>
			</div> 
			{% endblock %}


{% block scripts %}
	<script type="text/javascript">

	$(document).ready(function(){
		summary();
 
	}); 
	function summary(){
		$.ajax({
			url : "summary",
			type : "GET",
			success : function(data){
				$("#abc").html(data);
			}
		})
	}
	function updateCartItem(obj,id){
		$.ajax({
			url: "update/"+id+"/"+obj.value,
			type: "GET",
			data: {
				bookid: id,
				quantity: obj.value
			},
			success	:function(data){
				$("#"+(id.toString())).html(data);
				summary();
				totalCart();
			}
		})
	}

	</script>
{% endblock %}

newenv/cart/templates/cart/price.html
{{ price }} DH.

newenv/cart/templates/cart/summary.html
{% load customfunction %}
<ul class="list-group">
	<li class="list-group-item d-flex justify-content-between align-items-center"><h4>Résumé de la caisse</h4></li>
	<li class="list-group-item d-flex justify-content-between align-items-center">Livres<span>{{ cart|length }}</span></li>
	<li class="list-group-item d-flex justify-content-between align-items-center">Total<span>{{ cart.get_total_price }} DH.</span></li>
	<li class="list-group-item d-flex justify-content-between align-items-center">Expédition<span>{{ cost|shipping }} DH.</span></li>
	<li class="list-group-item d-flex justify-content-between align-items-center">Payable Total<span>{{ cart.get_total_price|payabletotal}} Dh.</span></li>
</ul>	

newenv/cart/templates/cart/totalcart.html
{{ cart|length }}