newenv/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    
	
	path('', views.cart_details, name='cart_details'),
	path('summary', views.cart_summary, name='cart_summary'),
	path('totalcart', views.total_cart, name='totalcart'),
	path('add/<int:bookid>', views.cart_add, name='cart_add'),
	path('remove/<int:bookid>', views.cart_remove, name='cart_remove'),
	path('update/<int:bookid>/<int:quantity>', views.cart_update, name='cart_update'),
 	path('remove/<int:bookid>/', views.cart_remove, name='cart_remove'),
 
 
]

newenv/order/urls.py
from django.urls import path
from . import views

app_name = 'order'

urlpatterns = [
	path('', views.order_list, name="order_list"),
	path('<int:id>', views.order_details, name="order_details"),
	path('shipping/', views.order_create, name="order_create"),
	path('pdf/<int:id>',views.pdf.as_view(), name="pdf"),
]

newenv/order/models.py
from django.db import models
from store.models import Book
from django.contrib.auth.models import User

from datetime import date
from django import forms




class Order(models.Model):
	customer = models.ForeignKey(User, on_delete = models.CASCADE)
	nom = models.CharField(max_length=30)
	email = models.EmailField()
	Telphone = models.CharField(max_length=16)
	address = models.CharField(max_length=150)
	region = models.CharField(max_length=20)
	ville = models.CharField(max_length=30)
	zip_code = models.CharField(max_length=30)
	payment_method = models.CharField(max_length = 20)
	N_compte= models.CharField(max_length = 20)
	transaction_id = models.IntegerField()
	payable = models.IntegerField()
	totalbook = models.IntegerField()
	created = models.DateField(auto_now_add=True)
	date_return = models.DateField(null=True, blank=True)
 
	updated = models.DateTimeField(auto_now=True)
	paid = models.BooleanField(default=False)
	chekbook = models.BooleanField(default=False)

	class Meta:
		ordering = ('-created','date_return' )

	def __str__(self):
		return 'Order {}'.format(self.id)

	def get_total_cost(self):
		return sum(item.get_cost() for item in self.items.all())





class Caisse(models.Model):
	date=models.DateField(auto_now=False,auto_created=False,auto_now_add=False,null=True,blank=True)
	checkout_day = models.DecimalField(max_digits=10, decimal_places=2,null=True)

	# def caisse():
	# 	total_cost = sum(order.get_total_cost() for order in Order.objects.filter(paid=True))
	# 	caisse = Caisse.objects.create(date=date.today(), caisse_jour=total_cost)
	# 	caisse.save()
	# 	return caisse


	def __str__(self):
		return 'Caisse {}'.format(self.id)


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return '{}'.format(self.id)

    def get_cost(self):
        return self.price

newenv/order/forms.py
from django import forms
from .models import Order

class OrderCreateForm(forms.ModelForm):
	DIVISION_CHOICES = (
		('	Casablanca-Settat', '	Casablanca-Settat'),
		('	Tanger-Tétouan-Al Hoceïma', 'Tanger-Tétouan-Al Hoceïma'),
		('	L\'Oriental', '	L\'Oriental '),
		('Fès-Meknès', 'Fès-Meknès'),
		('	Rabat-Salé-Kénitra', '	Rabat-Salé-Kénitra'),
		('	Béni Mellal-Khénifra', '	Béni Mellal-Khénifra '),
		('	Marrakech-Safi', '	Marrakech-Safi'),
		('	Drâa-Tafilalet', '	Drâa-Tafilalet'),
		('	Souss-Massa', '		Souss-Massa '),
 		 ('Guelmim-Oued Noun', 'Guelmim-Oued Noun'),
		('		Laâyoune-Sakia El Hamra', '	Laâyoune-Sakia El Hamra'),
		('	Dakhla-Oued Ed-Dahab', '	Dakhla-Oued Ed-Dahab')
	)

	DISCRICT_CHOICES = (
		('Casablanca', 'Casablanca'), 
		('Salé', 'Salé'),
		('Tanger', 'Tanger'),
  		('Marrakech', 'Marrakech'), 
		('Safi', 'Safi'),
		('Meknès', 'Meknès'),
  		('Oujda', '	Oujda'), 
		('Rabat', 'Rabat'),
		('	Agadir', 'Agadir'),
  		('Autre', 'Autre')
	)

	PAYMENT_METHOD_CHOICES = (
		('paypal ', 'paypal '),
		('Visa','Visa'),
		('MasterCard','MasterCard')
	)

	region = forms.ChoiceField(choices=DIVISION_CHOICES)
	ville =  forms.ChoiceField(choices=DISCRICT_CHOICES)
	payment_method = forms.ChoiceField(choices=PAYMENT_METHOD_CHOICES, widget=forms.RadioSelect())

	class Meta:
		model = Order
		fields = ['nom', 'email', 'Telphone', 'address', 'region', 'ville', 'zip_code','date_return', 'payment_method', 'N_compte', 'transaction_id']

newenv/order/views.py
from django.shortcuts import HttpResponse, render, redirect, get_object_or_404
from django.contrib.auth.models import User
from django.contrib import messages
from django.views import View
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from cart.cart import Cart
from .models import Order, OrderItem, Caisse
from .forms import OrderCreateForm
from .pdfcreator import renderPdf


# def order_create(request):
# 	cart = Cart(request)
# 	if request.user.is_authenticated:
# 		customer = get_object_or_404(User, id=request.user.id)
# 		form = OrderCreateForm(request.POST or None, initial={"name": customer.first_name, "email": customer.email})
# 		if request.method == 'POST':
# 			if form.is_valid():
# 				order = form.save(commit=False)
# 				order.customer = User.objects.get(id=request.user.id)
# 				order.payable = cart.get_total_price()
# 				order.totalbook = len(cart) # len(cart.cart) // number of individual book
# 				order.save()
				

# 				for item in cart:
# 					OrderItem.objects.create(
# 						order=order, 
# 						book=item['book'], 
# 						price=item['price'], 
# 						quantity=item['quantity']
# 						)
# 				cart.clear()
# 				return render(request, 'order/successfull.html', {'order': order})

# 			else:
# 				messages.error(request, "Fill out your information correctly.")

# 		if len(cart) > 0:
# 			return render(request, 'order/order.html', {"form": form})
# 		else:
# 			return redirect('store:books')
# 	else:
# 		return redirect('store:signin')
			
   
   ## addition pour moi 
   
   
def order_create(request):
    cart = Cart(request)
    if request.user.is_authenticated:
        customer = get_object_or_404(User, id=request.user.id)
        form = OrderCreateForm(request.POST or None, initial={"name": customer.first_name, "email": customer.email})
        if request.method == 'POST':
            if form.is_valid():
                order = form.save(commit=False)
                order.customer = User.objects.get(id=request.user.id)
                order.payable = cart.get_total_price()
                order.paid= True
                order.totalbook = len(cart) # len(cart.cart) // number of individual book
                order.save()

                for item in cart:
                    book = item['book']
                    quantity = item['quantity']
                    if book.stock < quantity:
                        messages.error(request, f"Pas assez de stock pour {book.title}.")
                        return redirect('store:cart')
                    book.stock -= quantity
                    book.save()
                    OrderItem.objects.create(
                        order=order, 
                        book=book, 
                        price=item['price'], 
                        quantity=quantity
                    )
                cart.clear()
                return render(request, 'order/successfull.html', {'order': order})

            else:
                messages.error(request, "Fill out your information correctly.")

        if len(cart) > 0:
            return render(request, 'order/order.html', {"form": form})
        else:
            return redirect('store:books')
    else:
        return redirect('store:signin')
   
   
   
   
   

def order_list(request):
	my_order = Order.objects.filter(customer_id = request.user.id).order_by('-created')
	paginator = Paginator(my_order, 5)
	page = request.GET.get('page')
	myorder = paginator.get_page(page)

	return render(request, 'order/list.html', {"myorder": myorder})

def order_details(request, id):
	order_summary = get_object_or_404(Order, id=id)

	if order_summary.customer_id != request.user.id:
		return redirect('store:index')

	orderedItem = OrderItem.objects.filter(order_id=id)
	context = {
		"o_summary": order_summary,
		"o_item": orderedItem
	}
	return render(request, 'order/details.html', context)

class pdf(View):
    def get(self, request, id):
        try:
            query=get_object_or_404(Order,id=id)
        except:
            Http404('Content not found')
        context={
            "order":query
        }
        article_pdf = renderPdf('order/pdf.html',context)
        return HttpResponse(article_pdf,content_type='application/pdf')
    
    

newenv/order/templates/order/change_form.html
{% extends 'admin/change_form.html' %}

{% block submit_buttons_bottom %}
    {{ block.super }} {# This calls super to get the default layout#}
    {# now let's add a button underneath it  #}
    <div  class="submit-row">  {# this button will POST request with the name 'execute' #}
       <input  type="submit"  value="Execute the rule"  name="execute">
    </div>
{% endblock %}

newenv/order/templates/order/details.html
{% extends 'store/base.html' %}
{% load static %}
{% load customfunction %}
{% block container %}
			<div class="row">
				<div class="col-sm-8">
					<div class="cart_info">
					    <table class="table table-hover">
					        <thead class="text-center">
					            <tr>
					                <th scope="col">#</th>
					                <th scope="col" style="width: 250px">Nom</th>
					                <th scope="col">Prix</th>
					                <th scope="col" >Qty</th>
					                <th scope="col"> Sub-Total</th>
					            </tr>
					        </thead>
					        <tbody class="text-center">
					        	{% for item in o_item %}
					            <tr>
					                <td class="cart_coverpage"><a href=""><img src="{{ item.book.coverpage.url}}"></a></td>
					                <td><a href="{% url 'store:book' id=item.book.id %}">{{ item.book.name }}</a></td>
					                <td class="cart_quantity">{{ item.book.price }} DH.</td>
					                <td class="cart_quantity">{{ item.quantity }}</td>
					                <td>{{ item.book.price|subtotal:item.quantity }} DH.</td>
					            </tr>
					            {% endfor %}
					        </tbody>
					    </table>
					</div>
				</div>
				<div class="col-sm-4">
					<ul class="list-group">
						<li class="list-group-item d-flex justify-content-between align-items-center"><h4>Résumé</h4></li>
						<li class="list-group-item d-flex justify-content-between align-items-center">Livres<span>{{ o_summary.totalbook }}</span></li>
						<li class="list-group-item d-flex justify-content-between align-items-center">Total<span>{{ o_summary.payable }} DH.</span></li>
						<li class="list-group-item d-flex justify-content-between align-items-center">Expédition<span>{{ 25 }} DH.</span></li>
						<li class="list-group-item d-flex justify-content-between align-items-center">Payable Total<span>{{ o_summary.payable|add:100 }} DH.</span></li>
						<li class="list-group-item d-flex justify-content-between align-items-center">Donnée Commande<span>{{ o_summary.created }}</span></li>

						

					</ul>
				</div>
			</div>
		{% endblock %}

newenv/order/templates/order/list.html
{% extends 'store/base.html' %}
{% load static %}
{% block container %}
			<div class="cart_info">
			    <table class="table table-hover">
			        <thead class="text-center">
			            <tr>
			                <th scope="col">#</th>
			                <th scope="col">Commande ID</th>
			                <th scope="col">Payer</th>
			                <th scope="col">Qty</th>
			                <th scope="col">Status</th>
			                <th scope="col">Date</th>
							<th scope="col">Date_Retourne</th>
							
			            </tr>
			        </thead>
			        <tbody class="text-center">
			            {% for morder in myorder %}
			            <tr>
			                <td>{{ forloop.counter }}</td>
			                <td><a href="{% url 'order:order_details' id=morder.id %}">#2023{{ morder.id }}</a></td>
			                <td>{{ morder.payable }} DH.</td>
			                <td>{{ morder.totalbook }}</td>
			                <td class="text-center">
			                	{% if morder.paid == True %}
			                	<p class="status3">Confirmé</p>
			                	{% else %}
			                	<p class="status1">Traitement</p>
			                	{% endif %}
			                </td>
			                <td>{{ morder.created }}</td>
							
							<td>{{ morder.date_return }}</td>
			            </tr>
			        	{% endfor %}
			        </tbody>
			    </table>
			</div>

			<div class="d-pagination">
			    <ul class="pagination">
				{% if myorder.has_previous %}
					<li class="page-item">
						<a class="page-link" href="?page=1">First</a>
					</li>								
					<li class="page-item">
						<a class="page-link" href="?page={{ myorder.previous_page_number }}">précédant</a>
					</li>
				{% endif %}
				{% for ord in myorder.paginator.page_range %}
					{% if myorder.number == ord %}
						<li class="page-item active">
							<span class="page-link">{{ ord }}
								<span class="sr-only">(actuel)</span>
							</span>
						</li>
					{% elif ord > myorder.number|add:'-3' and ord < myorder.number|add:'3' %}
						<li class="page-item">
							<a class="page-link" href="?page={{ ord }}">{{ ord }}</a>
						</li>

					{% endif %}

				{% endfor %}
				 {% if myorder.has_next %}
					<li class="page-item">
						<a class="page-link" href="?page={{ myorder.next_page_number }}">Suivant</a>
					</li>
					<li class="page-item">
						<a class="page-link" href="?page={{ myorder.paginator.num_pages }}">Dernier</a>
					</li>
				{% endif %}
			    </ul>
			</div>

		{% endblock %}

newenv/order/templates/order/order.html
{% extends 'store/base.html' %}
{% load static %}
{% load customfunction %}
{% load crispy_forms_tags %}



{% block container %}
			<div class="row">
			    <div class="col-md-8 order-md-1 cart_info">
			        <h4 class="mb-3 mt-3">adresse de livraison</h4>
					{% if messages %}
					<div class="messages">
					    {% for message in messages %}
					    <p{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
					    {% endfor %}
					</div>
					{% endif %}
			        <form action="" method="POST" class="needs-validation" novalidate="">
			        	{% csrf_token %}
						
			            <div class="row">
			                <div class="col-md-6 mb-3">
			                    {{ form.nom|as_crispy_field }}
			                </div>
			                <div class="col-md-6 mb-3">
			                  
			                   	{{ form.email|as_crispy_field }}
			                </div>
			            </div>
	           			<div class="mb-3">
			                {{ form.Telphone|as_crispy_field }}
			            </div>

			            <div class="mb-3">
			                {{ form.address|as_crispy_field }}
			            </div>
			            <div class="row">
			                <div class="col-md-5 mb-3">
								{{ form.region|as_crispy_field }}
			                </div>
			                <div class="col-md-4 mb-3">
								{{ form.ville|as_crispy_field }}
			                </div>
			                <div class="col-md-3 mb-3">
			                	{{ form.zip_code|as_crispy_field }}
			                </div>
			            </div>
			            <hr class="mb-4">
			            <div class="d-block my-3">
							{{ form.payment_method|as_crispy_field }}
			            </div>
			            <div class="row">
			                <div class="col-md-6 mb-3">
			                    {{ form.N_compte|as_crispy_field }}
			                  
			                </div>
			                <div class="col-md-6 mb-3">
			                    {{ form.transaction_id|as_crispy_field }}
			                </div>

							<div class="col-md-6 mb-3">
								<label for="{{ form.date_return.id_for_label }}">Date de retour</label>
								<input type="date" class="form-control" id="{{ form.date_return.id_for_label }}" name="{{ form.date_return.name }}" value="" readonly />
							</div>
							
							<script>
								var today = new Date();
								var returnDate = new Date(today.getTime() + 7 * 24 * 60 * 60 * 1000); // ajouter 7 jours
							
								var dd = returnDate.getDate();
								var mm = returnDate.getMonth()+1; //Janvier est 0 !
								var yyyy = returnDate.getFullYear();
							
								if(dd<10) {
									dd='0'+dd;
								} 
							
								if(mm<10) {
									mm='0'+mm;
								} 
							
								var returnDateFormatted = yyyy+'-'+mm+'-'+dd;
							
								document.getElementById("{{ form.date_return.id_for_label }}").value = returnDateFormatted;
							</script>
							
							
							
							
							
			            </div>
			            <hr class="mb-4">
			            <button class="btn btn-warning btn-block" type="submit" style="margin-bottom: 20px">Continuer à payer</button>
			        </form>
			    </div>
			    <div class="col-md-4 order-md-2 mb-4">
					<ul class="list-group">
						<li class="list-group-item d-flex justify-content-between align-items-center"><h4>Résumé de la caisse</h4></li>
						<li class="list-group-item d-flex justify-content-between align-items-center">Livres<span>{{ cart|length }}</span></li>
						<li class="list-group-item d-flex justify-content-between align-items-center">Total<span>{{ cart.get_total_price }} DH</span></li>
						<li class="list-group-item d-flex justify-content-between align-items-center">Expédition<span>{{ cost|shipping }} DH</span></li>
						<li class="list-group-item d-flex justify-content-between align-items-center">Total à payer<span>{{ cart.get_total_price|payabletotal}} DH</span></li>
					</ul>
			    </div>
			</div>
		{% endblock %}

newenv/order/templates/order/pdf.html
<!DOCTYPE html>
<html>
<head>
	<title>Book Store Sign In</title>
	{% load static  %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.min.css' %}">
</head>
<body>
	<div class="container">
		<div class="row justify-content-md-center">
	        <div class="col-md-12 cart_info">
		        <div class="ordered-info">
		                <h1>OrderID: 2023-{{ order.id }}</h1>
		                <h1>Livre: {{ order.totalbook }}</h1>
		                <h1>Nom: {{ order.nom }}</h1>
		                <h1>Numéro: {{ order.Telphone }}</h1>
		                <h1>E-mail: {{ order.email }}</h1>
		                <h1>N° Compte: {{ order.N_compte }}</h1>
		                <h1>Mode de Paiement: {{ order.payment_method }}</h1>

						<h1> Date return : {{ order.date_return}} </h1>

		                <h1>Adresse de Livraison: {{ order.region }}:{{ order.zip_code }}, {{ order.ville }}, {{ order.address }}</h1>
		        </div>
	        </div>
		</div>
	</div> 
</body>
</html>

newenv/order/templates/order/successfull.html
{% extends 'store/base.html' %}
{% load static %}

{% block container %}
        <div class="row">
            <div class="col-md-12 cart_info">
                    <div class="successful-order text-center">
                        <i class="fa fa-check"></i>
                        <h3 class="page-header">Merci pour votre achat!</h3>
                    </div>
                    <div class="ordered-info">
                        <h5>Commande-ID: <span>2023-{{ order.id }}</span></h5>
                        <h5>Livre: <span>{{ order.totalbook }}</span></h5>
                        <h5>Nom: <span>{{ order.nom }}</span></h5>
                        <h5>Numéro: <span>{{ order.Telphone }}</span></h5>
                        <h5>E-mail: <span>{{ order.email }}</span></h5>
                        <h5>N° Compte: <span>{{ order.N_compte}}</span></h5>
                        <h5>Mode de Paiement: <span>{{ order.payment_method }}</span></h5>
                        
                        <h5>Date return: <span>{{ order.date_return }}</span></h5>

                        <h5>Adresse de Livraison: <span>{{ order.region }}:{{ order.zip_code }}, {{ order.ville }}, {{ order.address }}</span></h5>
                    </div>
                    <div class="download-info">
                        <a href="{% url 'order:pdf' id=order.id %}"><i class="fa fa-download" aria-hidden="true"></i></a>
                    </div>
            </div>
        </div>
{% endblock %}